pr of irumeria
t-young31/soap-rust pull request #2
Opened 2023-01-04 14:18 UTC by irumeria

Totally 4 places are changed in this pr:

1. the usage of command line parser "clap" is updated with its version 4 features.
2. add a test for examining the rotation invariance of soap (in main.rs, function "test_rotate") 
3. (Important) The parameters "theta" and "phi" are exchanged in the function "to_polar". Since I think in the way you write the function "sphr_harm", "theta" should be the one that towards the positive Z axis. (Note that this exchange reduce the loss in the rotation invariance test, but the loss is still some kind of large)
4. Multiple neighbour elements can be selected now, by arg "--species" or "-s"

2023-01-04 17:49 UTC, t-young31 commented
hi @irumeria – thanks a lot for the PR. will take a look this weekend 

(oh and top GitHub tip: if you want to add more commits to this PR you can just push to your `iru` branch rather than closing it and reopening another!)

2023-01-05 01:43 UTC, irumeria commented
Oh, thank you for the tip.

2023-01-08 14:01 UTC, t-young31 requested changes
thanks again for the PR @irumeria – I've left a few comments but what's more critical is that the tests now no longer pass (assuming due to the theta<->phi swap). I've not looked into what the problem is there so any work on that would be appreciated!

2023-01-08 14:01 UTC, t-young31 commented on .gitignore
> +.vscode
needs a newline at the end of the file

2023-01-08 14:01 UTC, t-young31 commented on Cargo.toml
> +opt-level = "s"
why opt for binary size? Would have thought turning all optimisations would be best..?

2023-01-08 14:01 UTC, t-young31 commented on README.md
> +target/release/soap -f=./nacl_test.xyz -c=0 -s Na -s  Cl
I'm not a fan of having e.g. `-c=0` CLIs are usually `-c 0` is this behaviour supported?

2023-01-08 14:01 UTC, t-young31 commented on src/main.rs
> +
tests need to assert something!

2023-01-08 14:01 UTC, t-young31 commented on src/soap.rs
> +    pub fn power_spectrum_old(structure:      &Structure,
not a fan of having an `<X>_old` function – worth reconciling

2023-01-09 05:36 UTC, irumeria commented
Thanks for the helpful comments.

The direct cause for test failing is the pre-computed values of Monte Carlo integral do not match the analytic result whose theta and phi are swapped. It passed again after updating  the pre-computed values. I will recheck the comments and push to my branch later.

2023-01-11 08:48 UTC, t-young31 approved these changes
Looks great – thanks! 😄

2023-01-11 08:49 UTC, merged